export const SEED_PRODUCTS = [
  { id: "seed-1", name: "Banarasi Silk Saree", category: "fashion", price: 2499, original: 5999, rating: 4.9, reviews: 3452, badge: "Best Seller", shipping: "Free Shipping", stock: 156, desc: "Authentic Banarasi silk saree with intricate zari work. Handwoven by master artisans from Varanasi. Perfect for weddings and festive occasions.", img: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&q=80" },
  { id: "seed-2", name: "Vitamin C Brightening Serum", category: "beauty", price: 449, original: 899, rating: 4.8, reviews: 2783, badge: "Editor's Pick", shipping: "Free Shipping", stock: 234, desc: "10% Vitamin C serum with hyaluronic acid and vitamin E. Dermatologist-tested, cruelty-free. Brightens skin and reduces dark spots naturally.", img: "https://images.unsplash.com/photo-1570194065650-d99fb4ee8e39?w=600&q=80" },
  { id: "seed-3", name: "Cotton Printed Kurta Set", category: "fashion", price: 1299, original: 2499, rating: 4.7, reviews: 1834, badge: "Trending", shipping: "Free Shipping", stock: 98, desc: "Premium cotton kurta with matching pyjama. Hand-block printed with natural dyes. Breathable fabric perfect for daily wear.", img: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&q=80" },
  { id: "seed-4", name: "Noise-Cancelling Earbuds", category: "electronics", price: 1499, original: 2999, rating: 4.6, reviews: 4561, badge: "Hot Deal", shipping: "Free Shipping", stock: 312, desc: "Wireless earbuds with ANC, 40hr battery life, and IPX5 waterproof rating. Deep bass with custom-tuned drivers for Indian music.", img: "https://images.unsplash.com/photo-1588156979435-379b21e48341?w=600&q=80" },
  { id: "seed-5", name: "Brass Pooja Thali Set", category: "home", price: 899, original: 1799, rating: 4.9, reviews: 1243, badge: "Top Rated", shipping: "Free Shipping", stock: 87, desc: "Traditional brass pooja thali set with diya, kalash, and incense holder. Handcrafted in Moradabad. Includes 8 essential items.", img: "https://images.unsplash.com/photo-1603202655043-1d7ef8367b79?w=600&q=80" },
  { id: "seed-6", name: "Gold-Plated Jhumka Earrings", category: "fashion", price: 699, original: 1499, rating: 4.8, reviews: 3209, badge: "Best Seller", shipping: "Free Shipping", stock: 267, desc: "Traditional gold-plated jhumka earrings with meenakari work. Lightweight and elegant. Comes in a premium velvet box.", img: "https://images.unsplash.com/photo-1635767798638-3665ea302b6d?w=600&q=80" },
  { id: "seed-7", name: "Mixer Grinder 750W", category: "home", price: 2299, original: 3999, rating: 4.7, reviews: 5634, badge: "Best Seller", shipping: "Free Shipping", stock: 178, desc: "750W heavy-duty mixer grinder with 3 stainless steel jars. Ideal for Indian cooking — chutneys, masalas, and smoothies.", img: "https://images.unsplash.com/photo-1570222094111-d2b1d10f6e09?w=600&q=80" },
  { id: "seed-8", name: "Kumkumadi Night Face Oil", category: "beauty", price: 549, original: 999, rating: 4.8, reviews: 1989, badge: "Editor's Pick", shipping: "Free Shipping", stock: 145, desc: "Ayurvedic Kumkumadi tailam with saffron and sandalwood. Traditional recipe for glowing, radiant skin. Use nightly for best results.", img: "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600&q=80" },
  { id: "seed-9", name: "Kashmiri Pashmina Shawl", category: "fashion", price: 1899, original: 3999, rating: 4.9, reviews: 978, badge: "Top Rated", shipping: "Free Shipping", stock: 56, desc: "Authentic Kashmiri pashmina shawl hand-embroidered with floral patterns. Ultra-soft, lightweight, and keeps you warm in style.", img: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80" },
  { id: "seed-10", name: "Smart Band Pro", category: "electronics", price: 1999, original: 3999, rating: 4.5, reviews: 7201, badge: "Trending", shipping: "Free Shipping", stock: 423, desc: "Fitness tracker with SpO2, heart rate, sleep monitoring. 14-day battery, AMOLED display, IP68 water resistant. Made for India.", img: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&q=80" },
  { id: "seed-11", name: "Handcrafted Terracotta Diya Set", category: "home", price: 399, original: 799, rating: 4.9, reviews: 2102, badge: "Top Rated", shipping: "Free Shipping", stock: 312, desc: "Set of 10 hand-painted terracotta diyas with organic oil and cotton wicks. Proudly made by rural artisans from Punjab.", img: "https://images.unsplash.com/photo-1603202655043-1d7ef8367b79?w=600&q=80" },
  { id: "seed-12", name: "Natural Lip Balm Trio", category: "beauty", price: 299, original: 599, rating: 4.7, reviews: 3567, badge: "Trending", shipping: "Free Shipping", stock: 445, desc: "Set of 3 natural lip balms — mango, rose, and coconut. Made with shea butter and essential oils. No chemicals, 100% natural.", img: "https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?w=600&q=80" },
]
export const SEED_REVIEWS = [
  { name: "Priya Sharma", avatar: "PS", rating: 5, text: "Absolutely in love with the Banarasi saree! The zari work is breathtaking and the silk feels so premium. Perfect for my sister's wedding. Thank you LuxeDrop!", product: "Banarasi Silk Saree", date: "May 10, 2026" },
  { name: "Arjun Patel", avatar: "AP", rating: 5, text: "Ordered the earbuds and they arrived in 2 days! The noise cancellation is incredible for the price. Battery life is amazing too. Highly recommend!", product: "Noise-Cancelling Earbuds", date: "May 8, 2026" },
  { name: "Ananya Gupta", avatar: "AG", rating: 5, text: "The Kumkumadi oil has transformed my skin! Followed up with my dermatologist and she approved. Using it for a month and my friends keep asking my glow secret.", product: "Kumkumadi Night Face Oil", date: "May 5, 2026" },
  { name: "Rahul Verma", avatar: "RV", rating: 5, text: "Bought the mixer grinder for my mother. She's been using it daily for idli batter and chutneys. Powerful motor and easy to clean. Best purchase this year!", product: "Mixer Grinder 750W", date: "Apr 28, 2026" },
]
export const SEED_CATEGORIES = [
  { name: "Sarees", icon: "\uD83D\uDC55", color: "#e8b4b8", count: 89 },
  { name: "Kurtis", icon: "\uD83D\uDC57", color: "#f7d6e0", count: 124 },
  { name: "Jewelry", icon: "\uD83D\uDC8D", color: "#ffe0b2", count: 67 },
  { name: "Electronics", icon: "\uD83D\uDCF1", color: "#a8d8ea", count: 112 },
  { name: "Beauty", icon: "\uD83D\uDC84", color: "#f7d6e0", count: 156 },
  { name: "Home", icon: "\uD83C\uDFE0", color: "#c8e6c9", count: 78 },
]

export const fmt = (n) => "\u20B9" + Number(n).toLocaleString("en-IN")
export const disc = (p, o) => Math.round(((o - p) / o) * 100)
